version: "2"
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command:
      - mongod
  backend:
    build: "backend"
    environment:
      - NODE_ENV=production
      - MONGO_DATABASE=mongodb://mongodb/iot_test
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
  nginx:
    build: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./front/build:/app:ro
  mqtt:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /opt/conf/mqtt/config:/mosquitto/config
      - /opt/conf/mqtt/data:/mosquitto/data
      - /opt/conf/mqtt/log:/mosquitto/log
